-- vim.opt.cmdheight = 0
-- vim.opt.wildoptions = "fuzzy"
-- require("vim._core.ui2").enable({
--     msg = {
--         target = "cmd",
--         timeout = 8000,
--     }
-- })
--
-- vim.api.nvim_create_autocmd("FileType", {
--     pattern = "msg",
--     callback = function(ev)
--         vim.print("FIRED!!")
--         local winid = vim.fn.bufwinid(ev.buf)
--         vim.print(winid)
--         local win_config = vim.api.nvim_win_get_config(winid)
--         win_config.anchor = "NW"
--         win_config.relative = "editor"
--         win_config.focusable = true
--         win_config.row = 100
--         win_config.col = 0
--         win_config.width = 20
--         vim.print(win_config)
--         vim.api.nvim_win_set_config(winid, win_config)
--         vim.print(vim.api.nvim_win_get_config(winid))
--     end,
-- })
