#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require find-project-root

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -q | --quiet)
      LOG_INFO() { :; }
      LOG_WARN() { :; }
      LOG_DONE() { :; }
      quiet="true"
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      LOG_ERROR "Unknown option: $1" && exit 1
      ;;
    *)
      break
      ;;
  esac
done

main() {
  [[ "$#" -gt 1 ]] && LOG_ERROR "too many arguments (expected 1 or less)" && exit 1

  local project_root
  project_root=$(
    find-project-root "$PROJECT_ROOT_MARKER" 2>/dev/null ||
    find-project-root ".edis.json" 2>/dev/null ||
    find-project-root ".edis.toml" 2>/dev/null
  )

  if [[ -z "$project_root" ]]; then
    LOG_ERROR "root marker '$marker' not found" && exit 1
  fi

  local build_dir="$project_root/build"
  local project_name="$(basename $project_root)"
  local program_name="${1:-$project_name}"
  local program="$build_dir/$program_name"

  [[ ! -f "$program" ]] && LOG_ERROR "program not found: '$program_name'"      && exit 1
  [[ ! -x "$program" ]] && LOG_ERROR "program not executable: '$program_name'" && exit 1

  LOG_INFO "found program $program" \
  && LOG_INFO "executing program: $program_name" \
  && $program \
  && exit $?
}

main "$@"
