#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require fzf jq

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -b|--build)    build="$2";         shift 2; ;;
    -r|--run)      run="$2";           shift 2; ;;
    -c|--compiler) compiler="$2";      shift 2; ;;
    --build=*)     build="${1#*=}";    shift 1; ;;
    --run=*)       run="${1#*=}";      shift 1; ;;
    --compiler=*)  compiler="${1#*=}"; shift 1; ;;
    --) shift; break; ;;
    -*) LOG_ERROR "Unknown option: $1"; exit 1 ;;
    *) break; ;;
  esac
done

__create_edis_file() {
  local name="$(basename $1)"
  cat <<-EOF > .edis.toml
name = "$name"
build = "$2"
run = "$3"
compiler = "$4"
EOF
}

_create_edis_file() {
  jq -n \
  --arg name "$(basename $1)" \
  --arg build "$2" \
  --arg run "$3" \
  --arg compiler "$4" \
  '{
    "name": $name,
    "build": ($build | split(" ")),
    "run": ($run | split(" ")),
    "compiler": $compiler
  }' > .edis.json

}

main() {
  [[ "$#" -gt 1 ]] && LOG_ERROR "too many arguments (expected only 1)" && exit 1

  readonly COMPILERS=(
    "gcc"
    "g++"
    "javac"
    "python"
    "nasm"
  )
  readonly FZF_ARGS=(
    --height  "${FZF_HEIGHT:-$(( ${#COMPILERS[@]} + 4 ))}"
    --margin  "${FZF_MARGIN:-0,49%,0,1}"
    --pointer "${FZF_POINTER:->}"
    --border  "${FZF_BORDER:-bold}"
    --padding "${FZF_PADDING:-0}"
    --layout  "${FZF_LAYOUT:-reverse}"
    --info    "${FZF_INFO:-hidden}"
    --ghost   "${FZF_GHOST:-Select project type...}"
  )

  # use tail -1 to grab final query result even if not an option
  local compiler="${compiler:-$(printf "%s\n" "${COMPILERS[@]}" | fzf "${FZF_ARGS[@]}" --print-query | tail -1)}"
  [[ -z "$compiler" ]] && exit 1

  case "$compiler" in
    gcc)    require gcc;    default_build="gccb";  default_run="crun"; ;;
    g++)    require g++;    default_build="gppb";  default_run="crun"; ;;
    javac)  require javac;  default_build="javab"; default_run="javar"; ;;
    python) require python; echo $compiler >&2;    exit 0; ;;
    nasm)   require nasm;   echo $compiler >&2;    exit 0; ;;
    *) LOG_ERROR "unknown project type: $compiler"; exit 1; ;;
  esac

  [[ -z "$build" ]] && read -p "Build cmd ($default_build): " build && build="${build:-$default_build}"
  [[ -z "$run" ]]   && read -p "Run cmd ($default_run): " run       && run="${run:-$default_run}"

  local tmpdir="$(mktemp -d)"
  if [[ "$#" -eq 1 ]]; then
    path="$1"
    [[ -d "$path" ]] && LOG_ERROR "project '$path' already exists" && exit 1
  else
    read -p "Project path ($tmpdir): " path
    path="${path:-$tmpdir}"
    path="${path/#~/$HOME}"
  fi

  LOG_INFO "build cmd selected: $build"
  LOG_INFO "run cmd selected: $run"
  LOG_INFO "project path selected: $path"

  mkdir -p $path \
  && cd $path \
  && mkdir -p src/ build/ \
  && _create_edis_file "$path" "$build" "$run" "$compiler" \
  && LOG_DONE "created $compiler project in '$path'" \
  && echo "$(realpath .)" \
  && exit 0 \
  || exit 1
}

main "$@"
