#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/require.sh"
require fd


results=$(fd -t f --hidden "^.edis$|^.edis.toml$" "$HOME" "/tmp")
close_msg=$'\n\n\e[1;36mPress any key to close...\e[0m'
read -n 1 -s -p "$results$close_msg"

