#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require fd fzf

main() {
  readonly FZF_ARGS=(
  --height       "${FZF_HEIGHT:-50%}"
  --margin       "${FZF_MARGIN:-0,1,0,1}"
  --padding      "${FZF_PADDING:-0}"
  --pointer      "${FZF_POINTER:->}"
  --border       "${FZF_BORDER:-none}"
  --input-border "${FZF_INPUT_BORDER:-bold}"
  --layout       "${FZF_LAYOUT:-reverse}"
  --info         "${FZF_INFO:-hidden}"
  # --ghost "Select a project... (ctrl-bspace to go back)"
  --ghost        "${FZF_GHOST:-Select a project...}"
  --preview-window "${FZF_PREVIEW_WINDOW:-right:60%}"
  --preview-border "${FZF_PREVIEW_BORDER:-thinblock}"
  --preview 'cd {} && cd .. && eza -lah --tree --no-user --no-permissions --no-time --icons=auto --color=always $(basename {})'
  # --bind 'ctrl-bspace:become(edis)'
)
  local results
  results=$(fd -t f --hidden "^.edis$|^.edis.toml$" "$HOME" "/tmp")
  local selection=$(echo "$results" \
    | while read -r p; do dirname "$p"; done \
    | fzf "${FZF_ARGS[@]}" --print-query \
    | tail -1)

  [[ -n "$selection" ]] && selection=$(realpath "$selection") || exit 1
  [[ ! -d "$selection" ]] && LOG_ERROR "dir does not exist: $selection" && exit 1

  echo "$selection" && exit 0
}

main "$@"
