#!/usr/bin/env zsh

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require nvim edis

dir="$(edis)"
[[ -d "$dir/src" ]] && dir="$dir/src" || exit 1

nvim -c "cd $dir"

