#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require nvim fd

dir="$XDG_CONFIG_HOME/wallpapers"
[ ! -d $dir ] && {
    error "$dir does not exist"; exit $?
}

readonly FZF_ARGS=(
    --height "${FZF_HEIGHT:-50%}"
    --padding "${FZF_PADDING:-0}"
    --border "${FZF_BORDER:-none}"
    --margin "${FZF_MARGIN:-0}"
    --layout reverse
    --info hidden
    --delimiter /
    --with-nth=-1
    # --style=minimal
    --preview-border none
    --color "preview-bg:-1"
    --preview "fzf-preview {}"
    --preview-window "right:70%"
    --bind "enter:become(set-wallpaper.sh {})"
)

fd . -e "jpg" -e "png" -e "gif" "$dir" | fzf "${FZF_ARGS[@]}"
