#!/usr/bin/env bash

shopt -s globstar

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require find-project-root javac

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    -q | --quiet)
      LOG_INFO() { :; }
      LOG_WARN() { :; }
      LOG_DONE() { :; }
      quiet="true"
      shift
      ;;
    -qq | --qquiet)
      LOG_INFO() { :; }
      LOG_WARN() { :; }
      LOG_DONE() { :; }
      LOG_ERROR() { :; }
      qquiet="true"
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      LOG_ERROR "Unknown option: $1" && exit 1
      ;;
    *)
      break
      ;;
  esac
done

_compile_source_files() {
  local source_files=$1
  local source_dir=$2
  local build_dir=$3
  shift 3

  LOG_INFO "attempting to compile source files:"
  for source_file in $source_files; do
    local file_relative_to_src_dir="${source_file#$source_dir/}"
    [[ -z "$quiet" && -z "$qquiet" ]] && echo -e "\t$file_relative_to_src_dir -> ${file_relative_to_src_dir%.java}.class" >&2
  done

  local grep_main
  grep_main="$(grep -rE '^\s*public static void main' $source_dir)"
  [[ -z "$grep_main" ]]                 && LOG_WARN "no main method detected"
  [[ $(wc -l <<< "$grep_main") -gt 1 ]] && LOG_WARN "multiple main methods detected"

  # echo "javac -d $build_dir $@ $source_files"
  javac -d "$build_dir" "$@" $source_files || { LOG_ERROR "failed to compile"; return 1; }
}

main() {
  local project_root
  project_root=$(
    find-project-root "$PROJECT_ROOT_MARKER" 2>/dev/null ||
    find-project-root ".edis.json" 2>/dev/null ||
    find-project-root ".edis.toml" 2>/dev/null
  )
  if [[ -z "$project_root" ]]; then
    LOG_ERROR "root marker '$marker' not found"; exit 1
  fi

  local build_dir="$project_root/build"
  local source_dir="$project_root/src"
  local source_files=$project_root/src/**/*.java

  mkdir -p "$build_dir" \
  && LOG_INFO "building project into $build_dir..." \
  && _compile_source_files "$source_files" "$source_dir" "$build_dir" "$@" \
  && LOG_DONE "built project into $build_dir" \
  && exit 0
}

main "$@"
