-- autogenerated by $XDG_CONFIG_HOME/matugen/templates/nvim-colors.lua

local colors = {
    source_color = "#25449e",

    background    = "#121318",
    on_background = "#e3e1e9",
    shadow        = "#000000",

    primary      = "#b6c4ff",
    secondary    = "#c2c5dd",
    tertiary     = "#e3bada",
    error        = "#ffb4ab",
    on_primary   = "#1d2d61",
    on_secondary = "#2b3042",
    on_tertiary  = "#432740",
    on_error     = "#690005",

    -- https://github.com/chriskempson/base16/blob/main/styling.md
    base00 = "#893120", -- Default Background
    base01 = "#984630", -- Lighter Background (Used for status bars, line number and folding marks)
    base02 = "#a85b41", -- Selection Background
    base03 = "#b77051", -- Comments, Invisibles, Line Highlighting
    base04 = "#c78462", -- Dark Foreground (Used for status bars)
    base05 = "#d79972", -- Default Foreground, Caret, Delimiters, Operators
    base06 = "#e6ae82", -- Light Foreground (Not often used)
    base07 = "#f6c293", -- Light Background (Not often used)
    base08 = "#4e80d6", -- Semantics: Variables, Diff Deleted
    base09 = "#ec996e", -- Semantics: Literals
    base0a = "#88311f", -- Semantics: Classes
    base0b = "#f5c292", -- Semantics: Strings, Diff Inserted
    base0c = "#cc7769", -- Semantics: Escape Characters
    base0d = "#344b96", -- Semantics: Functions
    base0e = "#a1b152", -- Semantics: Keywords, Diff Changed
    base0f = "#7794d5", -- Semantics: Deprecated

    red        = "#ffb2b9",
    green      = "#a5d395",
    yellow     = "#cbcb76",
    blue       = "#bac3ff",
    magenta    = "#e4b7f3",
    cyan       = "#82d3e2",
    orange     = "#ffb4a5",
    on_red     = "#561d26",
    on_green   = "#11380b",
    on_yellow  = "#323200",
    on_blue    = "#222c61",
    on_magenta = "#442253",
    on_cyan    = "#00363e",
    on_orange  = "#561f14",

    primary_fixed       = "#dce1ff",
    primary_fixed_dim   = "#b6c4ff",
    secondary_fixed     = "#dee1f9",
    secondary_fixed_dim = "#c2c5dd",
    tertiary_fixed      = "#ffd7f6",
    tertiary_fixed_dim  = "#e3bada",
    on_primary_fixed    = "#03174b",
    on_secondary_fixed  = "#161b2c",
    on_tertiary_fixed   = "#2c122a",

    primary_container      = "#344479",
    secondary_container    = "#414659",
    tertiary_container     = "#5b3d57",
    error_container        = "#93000a",
    on_primary_container   = "#dce1ff",
    on_secondary_container = "#dee1f9",
    on_tertiary_container  = "#ffd7f6",
    on_error_container     = "#ffdad6",

    red_container        = "#72333b",
    green_container      = "#285020",
    yellow_container     = "#494900",
    blue_container       = "#394379",
    magenta_container    = "#5c386b",
    cyan_container       = "#004e59",
    orange_container     = "#733427",
    on_red_container     = "#ffdadc",
    on_green_container   = "#c0efb0",
    on_yellow_container  = "#e8e78f",
    on_blue_container    = "#dee0ff",
    on_magenta_container = "#f7d8ff",
    on_cyan_container    = "#9eefff",
    on_orange_container  = "#ffdad3",

    outline         = "#8f909a",
    outline_variant = "#45464f",

    inverse_primary = "#4c5c92",
    inverse_surface = "#e3e1e9",

    surface         = "#121318",
    surface_bright  = "#38393f",
    sufface_variant = "#45464f",

    surface_container_lowest  = "#0d0e13",
    surface_container_low     = "#1a1b21",
    surface_container         = "#1e1f25",
    surface_container_high    = "#292a2f",
    surface_container_highest = "#34343a",

}

return colors
