hl.on("hyprland.start", function()
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("hyprpm reload -n")
  hl.exec_cmd("mako")
  hl.exec_cmd("walker --gapplication-service")
  hl.exec_cmd("waybar")
end)
