require "autostart"
require "environment"
require "monitors"
require "look-n-feel"
require "input"
require "window-rules"
require "animations"
require "keybinds"
require "special-workspace"
-- require "plugins"
