preload = ~/.config/wallpapers/kanagawa.jpg
preload = ~/.config/wallpapers/ign_lonely-man.png
preload = ~/.config/wallpapers/ign_sunset.png
preload = ~/.config/wallpapers/nord_valley.png
preload = ~/.config/wallpapers/underwater.png
preload = ~/.config/wallpapers/Minimal-Nord.png
preload = ~/.config/wallpapers/current_wallpaper

wallpaper = , ~/.config/wallpapers/current_wallpaper
