# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = "caps:escape_shifted_capslock"
    kb_rules =

    repeat_rate = 35
    repeat_delay = 200

    follow_mouse = 2
    sensitivity = -0.2

    touchpad {
        disable_while_typing = true
        natural_scroll = true
    }
}

cursor {
    inactive_timeout = 5.0,
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
