# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 6
    gaps_out = 12

    border_size = 5
    # https://wiki.hypr.land/Configuring/Variables/#variable-types
    col.inactive_border = rgba(1a1d25ff)
    # col.inactive_border = rgba(15171eff)
    col.active_border = rgba(92b8c0ff)

    # https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
    # layout = master
    resize_on_border = true
    no_focus_fallback = true
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 2
    rounding_power = 3
    dim_inactive = true
    dim_strength = 0.2

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 2
        passes = 4
        # vibrancy = 0.1696
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
        # color = rgba(1a1a1aee)
    }
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = yes

    # https://wiki.hypr.land/Configuring/Animations/#curves
    #        NAME,           X0,   Y0,   X1,   Y1
    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    # https://wiki.hypr.land/Configuring/Animations/
    #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    animation = global,        1,     10,    default
    animation = border,        1,     2,  easeOutQuint
    animation = windows,       1,     4.79,  easeOutQuint
    animation = windowsIn,     1,     4.1,   easeOutQuint, popin 87%
    animation = windowsOut,    1,     5.49,  linear,       popin 87%
    animation = fadeIn,        1,     1.73,  almostLinear
    animation = fadeOut,       1,     1.46,  almostLinear
    animation = fade,          1,     1.03,  quick
    animation = layers,        1,     3.81,  easeOutQuint
    animation = layersIn,      1,     2.5,   easeOutQuint, fade
    animation = layersOut,     1,     1.5,   linear,       fade
    animation = fadeLayersIn,  0,     1.79,  almostLinear
    animation = fadeLayersOut, 0,     1.39,  almostLinear
    animation = workspaces,    1,     1.94,  almostLinear, fade
    animation = workspacesIn,  0,     2.0,   almostLinear, fade
    animation = workspacesOut, 0,     2.0,   almostLinear, fade
    animation = zoomFactor,    1,     7,     quick
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/#config
dwindle {
    pseudotile = true
    preserve_split = true
}

# https://wiki.hypr.land/Configuring/Master-Layout/#config
master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
