# autogenerated by $XDG_CONFIG_HOME/matugen/templates/fzf-colors.zsh

# fg_selected="{{colors.on_secondary_container.default.hex}}"
# bg_selected="{{colors.secondary_container.default.hex}}"
fg_selected="{{colors.on_primary_container.default.hex}}"
bg_selected="{{colors.primary_container.default.hex}}"
hl="{{colors.cyan.default.hex}}"
preview_bg="{{colors.surface_container.default.hex}}"
preview_fg="{{colors.on_surface_variant.default.hex}}"
prewiew_border="{{colors.secondary_container.default.hex}}"
list_border="{{colors.primary.default.hex}}"
input_border="{{colors.primary.default.hex}}"
pointer="{{colors.primary.default.hex}}"
