background #181d25
foreground #afb0b3
selection_background #2b3e57
selection_foreground #d7d8d9
# cursor #d7d8d9
# cursor #ed9a6b
cursor #d08770
cursor_text_color #080a0d

color0 #2d4f67
color1 #ff5d62
color2 #98bb62
color3 #e6c384
color4 #5394b4
color5 #d27e99
color6 #7aa89f
color7 #afb0b3

color8  #54576c
color9  #ff5d62
color10 #a8db46
color11 #ffd43b
color12 #24a1f2
color13 #eb9bb4
color14 #8fd9e6
color15 #ffffff
