background #272b31
foreground #aeb0b3
cursor #a9dfff
cursor_text_color #3c4653

color0 #0a0b0c
color1 #ff5d62
color2 #98BB6C
color3 #e6c384
color4 #67b5ed
color5 #bca6d6
color6 #7ccbcd
color7 #aeb0b3

color8 #3c4653
color9 #ff8f92
color10 #a7db58
color11 #f9e1ba
color12 #96cfff
color13 #d6c2ee
color13 #66edf0
color15 #a9dfff
