#!/usr/bin/env bash

_find_project_root="find-project-root"
_marker="${PROJECT_ROOT_MARKER:-.edis}"

source "$HOME/.local/scripts/lib/logging.sh"

if ! command -v "$_find_project_root" &> /dev/null; then
    error "could not find '$_find_project_root' command." && exit 1
fi

if ! command -v gcc &> /dev/null; then
    error "could not find 'gcc' command." && exit 1
fi

_compile_source_files()
{
    local project_root="$1"
    local source_dir="$2"
    local build_dir="$3"
    local has_errors=0

    info "attempting to compile source files:"
    while read -r file; do
        local filename="$(basename $file)"
        local obj_name="${filename%.c}.o"
        local file_relative_to_src_dir=$(realpath --relative-to="$source_dir" "$file")
        echo -e "\t$file_relative_to_src_dir -> ${file_relative_to_src_dir%.c}.o"
        # info "compiling src/$filename ⟶ build/$obj_name"
        gcc -c "$file" -o "$build_dir/$obj_name"
        if [ $? -ne 0 ]; then
            has_errors=1
        fi
    # here I'm doing some sort of "process subtitution" that
    # redirects the output of fd to read so that I can
    # set and return has_errors in the current shell's scope
    done < <(fd . -e "c" "$project_root/src")

    return $has_errors
}

_link_object_files()
{
    local project_root="$1"
    local build_dir="$2"
    local prog_name="$(basename $project_root)"

    gcc "$build_dir"/*.o -o "$build_dir/$prog_name"
    return $?
}

main()
{
    local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)
    local project_name="$(basename $project_root)"

    if [[ -z "$project_root" ]]; then
        error "root marker '$_marker' not found" && exit 1
    fi

    local build_dir="$project_root/build"
    local source_dir="$project_root/src"

    info "building project into $project_name/build..." \
    && (_compile_source_files "$project_root" "$source_dir" "$build_dir" || error "compiling failed") \
    && info "linking object files in $project_name/build..." \
    && (_link_object_files "$project_root" "$build_dir" || error "linking failed")\
    && success "program is $project_name/build/$project_name" \
    && exit 0
}

main "$@"

