#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require fzf

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -b | --build)
            build="$2"
            shift 2
            ;;
        -r | --run)
            run="$2"
            shift 2
            ;;
        -c | --compiler)
            compiler="$2"
            shift 2
            ;;
        --build=*)
            build="${1#*=}"
            shift 1
            ;;
        --run=*)
            run="${1#*=}"
            shift 1
            ;;
        --compiler=*)
            compiler="${1#*=}"
            shift 1
            ;;
        --)
            shift
            break
            ;;
        -*)
            exit $(error "Unknown option: $1")
            ;;
        *)
            break
            ;;
    esac
done

_create_edis_file() {
    local name="$(basename $1)"
    cat <<-EOF > .edis
name = $name
build = $2
run = $3
compiler = $4
EOF
}

main() {
    [[ "$#" -gt 1 ]] && exit $(error "too many arguments (expected only 1)")

    readonly COMPILERS=(
        "gcc"
        "gpp"
        "javac"
        "python"
    )
    local bname=$(basename $0)
    readonly FZF_ARGS=(
        --height "${FZF_HEIGHT:-$(( ${#COMPILERS[@]} + 4 ))}"
        --margin "${FZF_MARGIN:-0,49%,0,1}"
        --border "${FZF_BORDER:-bold}"
        --padding "${FZF_PADDING:-0}"
        --layout reverse
        --info hidden
        --print-query
        --pointer ">"
        --ghost "Select project type..."
        # --ghost "Select project type... (ctrl-bspace to go back)"
        # --bind 'ctrl-bspace:become(edis)'
    )


    # use tail -1 to grab final query result even if not an option
    local compiler="${compiler:-$(printf "%s\n" "${COMPILERS[@]}" | fzf "${FZF_ARGS[@]}" | tail -1)}"
    [[ -z "$compiler" ]] && exit 1

    case "$compiler" in
        gcc)
            default_build="gccb"
            default_run="crun"
            ;;
        gpp)
            echo $compiler >&2
            exit 0
            ;;
        javac)
            default_build="javab"
            default_run="javar"
            ;;
        python)
            echo $compiler >&2
            exit 0
            ;;
        *)
            exit $(error "unknown project type: $compiler")
            ;;
    esac

    [[ -z "$build" ]] && read -p "Build cmd ($default_build): " build && build="${build:-$default_build}"
    [[ -z "$run" ]]   && read -p "Run cmd ($default_run): " run       && run="${run:-$default_run}"

    [[ "$#" -eq 1 ]] && path="$1" || until [[ -n "$path" ]]; do read -p "Project name: " path; done
    path="${path/#~/$HOME}"
    [[ -d "$path" ]] && exit $(error "project '$path' already exists")

    info "initializing project '$path'" \
    && mkdir -p $path \
    && cd $path \
    && mkdir -p src/ build/ \
    && _create_edis_file "$path" "$build" "$run" "$compiler" \
    && success "created project '$path'" \
    && echo "$(realpath .)" \
    && exit 0 \
    || exit 1
}

main "$@"
