#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"

_create_edis_file()
{
    cat <<-EOF > .edis
name = $1
type = c
build = cb
run = cr
EOF
}

main()
{
    local readonly USAGE="Usage: $(basename $0) <project-name>"

    if [[ "$#" -eq 0 ]]; then
        error "need to give a project name\n\n$USAGE"
    fi

    if [[ "$#" -gt 1 ]]; then
        error "too many arguments (expected only 1)\n\n$USAGE"
    fi

    local arg="$1"
    if [[ "$arg" == "-h" || "$arg" == "--help" || "$arg" == "help" ]]; then
        echo "$USAGE"
        exit 0
    fi

    [[ -d "$arg" ]] && error "project '$arg' already exists in this directory"

    info "initializing project '$arg' in $(pwd)" \
    && mkdir -p $arg \
    && cd $arg \
    && mkdir -p src/ build/ \
    && _create_edis_file $arg \
    && success "created project '$arg' in '$(pwd)'" \
    && exit 0

}

main "$@"
