#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh" && require fzf

root_marker=".$(basename "$0")"

main() {
    readonly SUBCMDS=(
        "create"
        "select"
        "list"
        "init"
    )
    readonly FZF_ARGS=(
        --height "${FZF_HEIGHT:-$(( ${#SUBCMDS[@]} + 4 ))}"
        --margin "${FZF_MARGIN:-0,49%,0,1}"
        --border "${FZF_BORDER:-thinblock}"
        --padding "${FZF_PADDING:-0}"
        --layout reverse
        --info hidden
        --ghost "Enter subcmd..."
        --print-query
        --pointer ">"
    )

    # use tail -1 to grab final query result even if not an option
    local subcmd=$(printf "%s\n" "${SUBCMDS[@]}" | fzf "${FZF_ARGS[@]}" | tail -1)
    [[ -z "$subcmd" ]] && exit 1

    case "$subcmd" in
        create)
            edis-create
            ;;
        select)
            edis-select
            ;;
        list)
            edis-list
            ;;
        init)
            echo "init"
            ;;
        *)
            error "unknown subcmd: $subcmd"
            ;;
    esac
}

main "$@"
