#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"

_help() {
    cat <<-EOF
usage: $(basename "$0") [marker]

examples:
    $(basename "$0")
    $(basename "$0") .git
    $(basename "$0") .venv

EOF
}

_find_project_root() {

    local marker="${1:-$PROJECT_ROOT_MARKER}"

    if [[ -z "$marker" ]]; then
        error "PROJECT_ROOT_MARKER is not set, must pass root marker as argument."
    fi

    local current_dir=$(pwd -P) || error "pwd failed?"
    while [[ "$current_dir" != "/" ]]; do

        if [[ -e "$current_dir/$marker" ]]; then
            echo "$current_dir" && return 0
        fi

        current_dir=$(dirname "$current_dir")
    done

    error "could not locate '$marker' root marker."
}

main() {
    [[ "$1" == "help" ]] && _help && exit 0
    _find_project_root "$@"
}

main "$@"
