#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"

if ! hash fzf &> /dev/null; then
    error "missing dependency 'fzf'" 64
fi

height="${1:-75%}"
if [[ -z "$1" ]]; then
    padding="1,0,1,0"
else
    padding="1,3"
fi


readonly QUERY='dnf --cacheonly --quiet repoquery --qf %{name}\n'
readonly PREVIEW="dnf --cacheonly --quiet info"

readonly fzf_args=(
    --height="$height"
    --padding="$padding"
    --layout=reverse
    --preview "$PREVIEW {1}"
    --preview-window "down:65%"
    --preview-border="thinblock"
    --input-border="bottom"
    --input-label " Fedora DNF packages "
    --bind="enter:become(sudo dnf --quiet -y install {})"
)

$QUERY | fzf "${fzf_args[@]}"
