#!/usr/bin/env bash

source "$HOME/.local/scripts/lib/logging.sh"

if ! hash nvim &> /dev/null; then
    error "missing dependency 'nvim'" 64
fi

if ! hash fd &> /dev/null; then
    error "missing dependency 'fd'" 64
fi

dir="$XDG_CONFIG_HOME/wallpapers"
[ ! -d $dir ] && error "$dir does not exist"

height="${1:-50%}"
if [[ -z "$1" ]]; then
    padding="0"
else
    padding="1,3"
fi

readonly fzf_args=(
    --height=$height
    --layout=reverse
    --delimiter /
    --with-nth=-1
    # --style=minimal
    --border=none
    --padding="$padding"
    --preview-border=none
    --preview "fzf-preview {}"
    --preview-window "right:70%"
    --bind="enter:become(wallpaper {})"
)

fd . -e "jpg" -e "png" -e "gif" "$dir" | fzf "${fzf_args[@]}"
