#!/usr/bin/env zsh

source "$HOME/.local/scripts/lib/logging.sh"

if ! hash nvim &> /dev/null; then
    error "missing dependency 'nvim'" 64
fi

if ! hash fd &> /dev/null; then
    error "missing dependency 'fd'" 64
fi

height="${1:-50%}"
if [[ -z "$1" ]]; then
    padding="0"
else
    padding="1,3"
fi

TAB=$'\t'
readonly fzf_args=(
    --height="$height"
    --layout=reverse
    --padding="$padding"
    # --preview="bat --color=always --style=numbers $dir/{1} 2>/dev/null || eza -lF --color=always $dir/{}"
    --preview "bat --color=always --style=numbers {} 2>/dev/null || eza --tree --color=always --level 3 $dir/{}"
    --preview-window="right:60%:wrap"
    --preview-border='thinblock'
    --wrap-sign="$TAB "
    --tabstop=4
    --bind="enter:become(nvim {})"
)

fd -t f --hidden "^.edis$" "$HOME" | fzf "${fzf_args[@]}"
