#!/usr/bin/env bash

shopt -s globstar

_find_project_root="find-project-root"
_marker="${PROJECT_ROOT_MARKER:-.edis}"

source "$HOME/.local/scripts/lib/logging.sh"

if ! command -v "$_find_project_root" &> /dev/null; then
    error "could not find '$_find_project_root' command." && exit 1
fi

if ! command -v javac &> /dev/null; then
    error "could not find 'javac' command." && exit 1
fi

_compile_source_files()
{
    # this breaks relative imports for the compiler for some reason
    local source_files=$1
    local source_dir=$2
    local build_dir=$3

    info "attempting to compile source files:"
    for source_file in $source_files; do
        local file_relative_to_src_dir=$(realpath --relative-to="$source_dir" "$source_file")
        echo -e "\t$file_relative_to_src_dir -> ${file_relative_to_src_dir%.java}.class"
    done

    local grep_result="$(grep -rE '^\s*public static void main' $source_dir)"
    if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
        warning "multiple main methods detected"
    fi

    javac -d $build_dir $source_files && return 0 || error "failed to compile" && return 1
}

main()
{
    local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)

    if [[ -z "$project_root" ]]; then
        error "root marker '$_marker' not found" && exit 1
    fi

    local build_dir="$project_root/build"
    local source_dir="$project_root/src"
    local source_files=$project_root/src/**/*.java

    # && javac -d $build_dir $source_files || error "failed to compile" \
    mkdir -pv "$build_dir" \
    && info "building project into $build_dir..." \
    && _compile_source_files "$source_files" "$source_dir" "$build_dir" \
    && success "built project into $build_dir" \
    && exit 0
}

main "$@"
