#!/usr/bin/env bash


_marker="${PROJECT_ROOT_MARKER:-.edis}"

source "$HOME/.local/scripts/lib/logging.sh"
source "$HOME/.local/scripts/lib/require.sh"
require find-project-root java

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -q | --quiet)
            info() { return 0; }
            warning() { return 0; }
            success() { return 0; }
            quiet="true"
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            error "Unknown option: $1" && exit 1
            ;;
        *)
            break
            ;;
    esac
done

main() {
    [[ "$#" -gt 1 ]] && error "too many arguments (expected 1 or less)" && exit 1

    local project_root=$(find-project-root "$_marker" 2>/dev/null)

    if [[ -z "$project_root" ]]; then
        error "root marker '$_marker' not found" && exit 1
    fi

    local build_dir="$project_root/build"
    local src_dir="$project_root/src"

    if [[ "$#" -eq 0 ]]; then
        local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"

        if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
            error "multiple main methods detected" && return 1
        fi

        if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
            error "no main method detected" && return 1
        fi

        local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
        local main_name=$(basename "$main_file" ".java")
    else
        local main_name="$1"
    fi
    local main_class=$(find "$build_dir" -name "$main_name.class")
    [[ -z "$main_class" ]] && error "could not locate class file: 'build/$main_name.class'"
    local rel_path_to_main="${main_class#$build_dir/}"
    rel_path_to_main="${rel_path_to_main%.*}"

    info "class path: $build_dir" \
    && info "executing main() in: $rel_path_to_main" \
    && java -cp "$build_dir" "$rel_path_to_main" \
    && return 0
}

main "$@"
