#!/usr/bin/env bash


_find_project_root="find-project-root"
_marker="${PROJECT_ROOT_MARKER:-.edis}"

error()
{
    local errmsg="$1"
    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
    exit 1
}

if ! command -v "$_find_project_root" &> /dev/null; then
    error "could not find '$_find_project_root' command"
fi

if ! command -v java &> /dev/null; then
    error "could not find 'java' command"
fi

main()
{
    local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)

    if [[ -z "$project_root" ]]; then
        error "root marker '$_marker' not found"
    fi

    local build_dir="$project_root/build"
    # local src_dir="$project_root/src/main/java"
    local src_dir="$project_root/src"
    local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"

    if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
        error "multiple main methods detected"
    fi

    if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
        error "no main method detected"
    fi

    local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
    local main_name=$(basename "$main_file" ".java")
    local main_class=$(find "$build_dir" -name "$main_name.class")
    local rel_path_to_main="${main_class#$build_dir/}"
    rel_path_to_main="${rel_path_to_main%.*}"

    java -cp "$build_dir" "$rel_path_to_main" && return 0
}

main "$@"
