#!/usr/bin/env bash

shopt -s globstar

_find_project_root="find-project-root"
_marker="${PROJECT_ROOT_MARKER:-.edis}"

error()
{
    local msg="$1"
    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $msg >&2
    exit 1
}

info()
{
    local msg="$1"
    echo -e "[\e[1;34mINFO\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
    return 0
}

success()
{
    local msg="$1"
    echo -e "[\e[1;32mSUCCESS\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
    return 0
}

if ! command -v "$_find_project_root" &> /dev/null; then
    error "could not find '$_find_project_root' command."
fi
if ! command -v javac &> /dev/null; then
    error "could not find 'javac' command."
fi

_compile_source_files()
{
    # this breaks relative imports for the compiler for some reason
    local source_files=$1
    local build_dir=$2

    for source_file in $source_files; do
        echo "javac -d $build_dir $source_file"
        javac -d $build_dir $source_file || error "javac failed"
        info "compiled $(basename $source_file)"
    done

    return 0
}

main()
{
    local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)

    if [[ -z "$project_root" ]]; then
        error "root marker '$_marker' not found"
    fi

    local build_dir="$project_root/build"
    local source_files=$project_root/src/**/*.java

    # && _compile_source_files "$source_files" "$build_dir" \
    mkdir -pv "$build_dir" \
    && info "building project into $build_dir..." \
    && javac -d $build_dir $source_files \
    && success "built project into $build_dir" \
    && exit 0
}

main "$@"
